### ISSUE TITLE
Cant delete pending providers

### ISSUE THREAD

**Issue by WjohnsonKPN** [zkeene/qualitydb#22]
Error: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`kpnquality`.`performances`, CONSTRAINT `performances_ibfk_1` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`))

**Comment by zkeene** [comment]
Example Koh,Isaac

This behavior is expected to prevent the database from cascade deleting multiple related records. 

Example provider appeared to not have any related performance data when looking at the provider detail screen. Direct DB query revealed a performance record did exist. It is not appearing due to issue #10 . Will fix issue #10 so related records are visible and can be deleted first. Disabling referential integrity checks could cause the database to become corrupt.

**Comment by zkeene** [comment]
Issue #10 fixed, this fixes the system so related records are shown and can be deleted first. Resolving issue.
